name: Continuous Integration
on:
  push:
    branches:
      - master
      - my_theme
  pull_request:
    branches:
      - master
      - my_theme
jobs:
  build:
    name: "Build theme"
    runs-on: "ubuntu-latest"
    env:
      JEKYLL_VERSION: "~> 4.2"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set Up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Run build
        run: gem build my_theme.gemspec
